name: Posta
options:
  bundleIdPrefix: com.posta
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    # Code Signing Settings - Update these with your values
    DEVELOPMENT_TEAM: "456SHKPP26"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    PROVISIONING_PROFILE_SPECIFIER: ""
    
    # App Settings
    PRODUCT_BUNDLE_IDENTIFIER: com.posta.app
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
packages:
  NDKSwift:
    url: https://github.com/pablof7z/NDKSwift
    from: 0.2.0
targets:
  Posta:
    type: application
    platform: iOS
    sources: 
      - Sources/Posta
    dependencies:
      - package: NDKSwift
        product: NDKSwift
      - package: NDKSwift
        product: NDKSwiftUI
    info:
      path: Sources/Posta/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIRequiredDeviceCapabilities:
          - arm64
    settings:
      base:
        INFOPLIST_FILE: Sources/Posta/Info.plist
        PRODUCT_NAME: Posta
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false