name: Deploy to TestFlight

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor, major)'
        required: false
        default: 'patch'

jobs:
  deploy:
    name: Deploy to TestFlight
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    
    - name: Install dependencies
      run: |
        brew install xcodegen
        brew install xcbeautify
    
    - name: Setup API Key
      env:
        APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > ~/.appstoreconnect/private_keys/AuthKey_6VZ4NHWMQN.p8
    
    - name: Generate Xcode project
      run: ./refresh-project.sh
    
    - name: Build and deploy
      env:
        API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APP_STORE_API_ISSUER_ID }}
      run: |
        xcodebuild archive \
          -project Posta.xcodeproj \
          -scheme Posta \
          -configuration Release \
          -archivePath build/Posta.xcarchive \
          -destination "generic/platform=iOS" \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM="6VZ4NHWMQN" \
          | xcbeautify
        
        xcodebuild -exportArchive \
          -archivePath build/Posta.xcarchive \
          -exportPath build \
          -exportOptionsPlist ExportOptions-TestFlight.plist \
          | xcbeautify
        
        xcrun altool --upload-app \
          -f build/Posta.ipa \
          -t ios \
          --apiKey "$API_KEY_ID" \
          --apiIssuer "$API_ISSUER_ID"